### PR TITLE
[doc] Assure that users know the command is pm2 install

### PR DESCRIPTION
**Pull request by richardpringle**
This is really stupid and maybe there's a better way to do this, but I've actually spoken with multiple people who have made this mistake.

If you feel that users should be smarter than that, please just close this PR. However, as I said, multiple people have made the same mistake.

Cheers

### CODE REVIEW

**Comment by richardpringle** [comment]
Thanks @Martii

**Comment by richardpringle** [comment]
Hey @Martii, any chance we can get this merged? Otherwise I'm just going to close it.

**Comment by Martii** [comment]
@richardpringle 
I don't have push permissions but it is always good to be very clear. The first commit on this repo is @Unitech so that would be the person to mention.

**Comment by richardpringle** [comment]
@vmarchaud?

**Comment by Unitech** [comment]
You're right, merged

**Pull request merged**
