### PR TITLE
Fix logs ratain on Windows platform

### PR DESCRIPTION
**Pull request by tsing**
@jgoehringer suggested the way to fix it on #56 

I tested on Windows and it works.

### CODE REVIEW

**Comment by tsing** [comment]
@vmarchaud @Unitech Can you take a look at this?

**Comment by Unitech** [comment]
@vmarchaud @wallet77 could you try this PR on linux to see if it works as expected? thx

**Comment by Martii** [comment]
@Unitech 

CLI test from Linux...

``` sh-session
$ node -e 'var path = require("path"); console.log(path.sep)'
/
```

**Comment by thfrei** [comment]
👍 Tested on Windows and it works. Please consider a merge. Thanks!

**Comment by thfrei** [comment]
@Unitech please consider merge. Linux test was successfull (it returned `'/'`
I can totally understand if there is a lot todo. But the issue was solved over half a year ago and has not been merged since. Thank you.

**Comment by Unitech** [comment]
closed in favor of https://github.com/keymetrics/pm2-logrotate/pull/120

**Pull request closed without merging**
